# Site settings
title: Nice Blog
name: Nice Blog # your name
email: youremail@example.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl:
remote_theme: Gabriel-Chen/Nice_Blog
url: "https://github.com/LimYujin"
twitter_username: # your Twitter username
github_username: "LimYujin" # your Github username
disqus_username: # your disqus username

google-analytics: # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
