# Site settings
title: YJ SW Blog
name: LimYujin # your name
email:
description: >
    Yijin SW record
baseurl:
remote_theme: Gabriel-Chen/Nice_Blog
url: "https://github.com/LimYujin"
twitter_username: # your Twitter username
github_username: "LimYujin" # your Github username
disqus_username: # your disqus username

google-analytics: # add it if you have one
google_fonts: "Nanum+Gothic:400,700"

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
